def help():
    print()
    print('\033[1mSanelotto\033[0m - application for auto-deploying. Sanelotto works in conjunction with Continuous-Integration systems.')
    print()
    print('\033[1mSYNOPSIS\033[0m')
    print()
    print('sanelotto generate')
    print('- Start question-answer mode to generate a new project.')
    print()
    print('sanelotto create [NAME]')
    print('- Create project template with your project-name.')
    print()
    print('sanelotto start [TYPE]')
    print('- Start project form current directory. Type: "local" or "server"')
    print()
    print('sanelotto version')
    print('- Print Sanelotto version')
    print()
    print('sanelotto uninstall')
    print('- Uninstall Sanelotto')
    print()
    print('sanelotto help')
    print('- Print Sanelotto help')
    print()
    print('\033[1mAUTHOR\033[0m')
    print('Vladimir37')
    print('MIT License')
    print()
    print('\033[1mDOCUMENTATION\033[0m')
    print('You can find full documentation on http://sanelotto.info')
    print()